name: build-qt5

on:
  pull_request:
    types: [opened, synchronize, reopened]

stages:
  - build

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build Qt5 Docker image
        run: |
          docker version
          docker build -f qt5/Dockerfile .
