name: build-ubuntu-qt5

on:
    pull_request:
      branches:
        - main
      paths:
        - 'qt5/*'
jobs:
    build-ubuntu:
      runs-on: docker:29.7.0-dind
      steps:
        - name: build
          run: |
            docker build -f qt5/Dockerfile .
