name: build-ubuntu-qt5

on:
    pull_request:
        types: [opened, synchronize, reopened]
    paths:
      - 'qt5/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build Docker image
        run: |
          docker version
          docker build -f qt5/Dockerfile .
